apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: database-seed
  name: database-seed
spec:
  containers:
    - env:
        - name: API_GATEWAY_PORT
          valueFrom:
            configMapKeyRef:
              key: API_GATEWAY_PORT
              name: env
        - name: API_GATEWAY_URI
          valueFrom:
            configMapKeyRef:
              key: API_GATEWAY_URI
              name: env
        - name: CDN_HOST
          valueFrom:
            configMapKeyRef:
              key: CDN_HOST
              name: env
        - name: CDN_PORT
          valueFrom:
            configMapKeyRef:
              key: CDN_PORT
              name: env
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              key: DATABASE_URL
              name: env
        - name: DIGITAL_IDENTITY_SERVICE_CONTAINER_ORIGIN
          valueFrom:
            configMapKeyRef:
              key: DIGITAL_IDENTITY_SERVICE_CONTAINER_ORIGIN
              name: env
        - name: DIGITAL_IDENTITY_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              key: DIGITAL_IDENTITY_SERVICE_PORT
              name: env
        - name: FRONTEND_CLIENT_PORT
          valueFrom:
            configMapKeyRef:
              key: FRONTEND_CLIENT_PORT
              name: env
        - name: NEXT_PUBLIC_API_GATEWAY_URI
          valueFrom:
            configMapKeyRef:
              key: NEXT_PUBLIC_API_GATEWAY_URI
              name: env
        - name: ORDERS_SERVICE_CONTAINER_ORIGIN
          valueFrom:
            configMapKeyRef:
              key: ORDERS_SERVICE_CONTAINER_ORIGIN
              name: env
        - name: ORDERS_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              key: ORDERS_SERVICE_PORT
              name: env
        - name: ORDER_HISTORY_SERVICE_CONTAINER_ORIGIN
          valueFrom:
            configMapKeyRef:
              key: ORDER_HISTORY_SERVICE_CONTAINER_ORIGIN
              name: env
        - name: ORDER_HISTORY_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              key: ORDER_HISTORY_SERVICE_PORT
              name: env
        - name: PAYMENTS_SERVICE_CONTAINER_ORIGIN
          valueFrom:
            configMapKeyRef:
              key: PAYMENTS_SERVICE_CONTAINER_ORIGIN
              name: env
        - name: PAYMENTS_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              key: PAYMENTS_SERVICE_PORT
              name: env
        - name: POSTGRES_PG_ADMIN_PORT
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PG_ADMIN_PORT
              name: env
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PORT
              name: env
        - name: PRODUCTS_SERVICE_CONTAINER_ORIGIN
          valueFrom:
            configMapKeyRef:
              key: PRODUCTS_SERVICE_CONTAINER_ORIGIN
              name: env
        - name: PRODUCTS_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              key: PRODUCTS_SERVICE_PORT
              name: env
        - name: PROFILE_SERVICE_CONTAINER_ORIGIN
          valueFrom:
            configMapKeyRef:
              key: PROFILE_SERVICE_CONTAINER_ORIGIN
              name: env
        - name: PROFILE_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              key: PROFILE_SERVICE_PORT
              name: env
        - name: PROJECT_ID
          valueFrom:
            configMapKeyRef:
              key: PROJECT_ID
              name: env
        - name: REDIS_CONNECTION_URI
          valueFrom:
            configMapKeyRef:
              key: REDIS_CONNECTION_URI
              name: env
        - name: REDIS_INSIGHT_PORT
          valueFrom:
            configMapKeyRef:
              key: REDIS_INSIGHT_PORT
              name: env
      image: gcr.io/central-beach-194106/redis-ms-cqrs-database_seed:latest
      imagePullPolicy: Always
      name: database-seed
      resources: {}
  #restartPolicy: OnFailure
  restartPolicy: Never
status: {}
