apiVersion: v1
data:
  API_GATEWAY_PORT: "3000"
  API_GATEWAY_URI: http://api-gateway.default.svc.cluster.local:3000
  CDN_HOST: cdn
  CDN_PORT: "80"
  DATABASE_URL: postgresql://postgres:postgres@${_CLOUDSQL_POSTGRESQL_IP}:5432/dbFashion?schema=public 
  DIGITAL_IDENTITY_SERVICE_CONTAINER_ORIGIN: http://digital-identity-service
  DIGITAL_IDENTITY_SERVICE_PORT: "3005"
  FRONTEND_CLIENT_PORT: "4200"
  NEXT_PUBLIC_API_GATEWAY_URI: http://${_API_GATEWAY_IP}:3000
  ORDER_HISTORY_SERVICE_CONTAINER_ORIGIN: http://order-history-service
  ORDER_HISTORY_SERVICE_PORT: "3002"
  ORDERS_SERVICE_CONTAINER_ORIGIN: http://orders-service
  ORDERS_SERVICE_PORT: "3001"
  PAYMENTS_SERVICE_CONTAINER_ORIGIN: http://payments-service
  PAYMENTS_SERVICE_PORT: "3004"
  POSTGRES_PG_ADMIN_PORT: "5200"
  POSTGRES_PORT: "5432"
  PRODUCTS_SERVICE_CONTAINER_ORIGIN: http://products-service
  PRODUCTS_SERVICE_PORT: "3003"
  PROFILE_SERVICE_CONTAINER_ORIGIN: http://profile-service
  PROFILE_SERVICE_PORT: "3006"
  PROJECT_ID: ${PROJECT_ID}
  REDIS_CONNECTION_URI: ${_REDIS_URI}
  REDIS_INSIGHT_PORT: "${_REDIS_INSIGHT_PORT}"
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: api-gateway-env
  name: env
