apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: postgresql-pg-admin-gui
  name: postgresql-pg-admin-gui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgresql-pg-admin-gui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: postgresql-pg-admin-gui
    spec:
      containers:
        - env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: user@domain.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: password
          image: dpage/pgadmin4
          name: postgresql-pg-admin-gui
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
